# Evaluating Chunking Methods

This notebook evaluates how three different chunking methods (fixed-size, markdown-based, and LLM-semantic) affects performance in a baking assistant RAG system. The evaluation uses batch replay test prompts—multi-turn conversations that include both the ideal model response and the ideal chunk(s) that should be retrieved.

## Which Metrics were used:
There are two ways we are measuring the chunks affect on LLM's RAG performance:
A) Quatitative Metrics (Token-Level Chunk Comparison):
Since the goal is to measure chunking quality, we compare for each turn in the conversation the chunks that were returned by the AI system and the ideal chunk that we would have wanted. Therefore, the all metrics are token-level comparison between the retrieved chunks vs. ideal chunks:

* Precision: proportion of retrieved tokens that are correct.

* Recall: proportion of gold tokens successfully retrieved

* F1 score: harmonic mean of precision and recall.

* ROUGE-L: longest common subsequence overlap between retrieved and ideal chunk text. (Sequence-based similarity metric)

* IoU (token overlap): overall overlap between retrieved and gold tokens

These metrics directly measure how well each chunking method supports accurate retrieval.

#### Definitions

- $t_e$: set of gold (highlight) tokens  
- $t_r$: set of retrieved tokens  
- $q$: a specific query  
- $\mathbf{C}$: the chunked corpus (document split into chunks)

$\text{Precision}_q(\mathbf{C}) = \frac{|t_e \cap t_r|}{|t_r|}$

$\text{Recall}_q(\mathbf{C}) = \frac{|t_e \cap t_r|}{|t_e|}$

$F1_q(\mathbf{C}) = 2 \cdot \frac{\text{Precision}_q(\mathbf{C}) \cdot \text{Recall}_q(\mathbf{C})}{\text{Precision}_q(\mathbf{C}) + \text{Recall}_q(\mathbf{C})}$

###### Longest Common Subsequence (LCS) based similarity metric.

$\text{ROUGE-L}_q(\mathbf{C}) = \frac{\text{LCS}(t_e, t_r)}{\max(|t_e|, |t_r|)}$

$\text{IoU}_q(\mathbf{C}) = \frac{|t_e \cap t_r|}{|t_e \cup t_r|}$

B) Qualitative Metrics: 
To understand whether chunking affects downstream model performance, we evaluate the assistant’s final answers using an LLM-as-a-Judge. This step matters because poor chunking does not always translate to poor answers, and vice versa. However, the system prompt forced the model to rely only on retrieved knowledge (except for greetings). This isolates the effect of chunking. 

In real user testing, the model was allowed to fall back on internal knowledge with appropriate disclaimers.

The LLM-as-a-Judge checked for 3 different metrics on a score from 1-5:
* Groundedness (Chunk Alignment): How much does the answer reflect the ideal chunk? The LLM judge should use just the ideal chunk and the baking LLM response to evaluate this. 

* Factual Accuracy: Does the answer preserve correct information? e.g. correct measurements or oven temperatures. The LLM judge should use just the ideal response and the baking LLM response to evaluate this. 

* Helpfulness: Is the answer still useful to the user, given the restricted context? The LLM judge should use the users query and previous dialogue history to determine if the baking LLM's response was helpful.  

Therefore, the LLM-as-a-Judge has access to the current conversation history, the ideal chunk, the ideal response, and LLM's actual response, and the User query.

## Why Two Test Batches?
1) Batch 1 — Natural Conversation (called Batch_test_1_mix)
This batch simulates realistic user interaction, including greetings, off-topic questions, and mistakes. Some turns have no ideal chunk (NA) because the question is off-topic or a greeting. This is important to evaluate how the model behaves in realistic user interaction (E.g. if the question is not relevant does it correctly re-direct the user?). 
It checks: 
* Conversational appropriateness
* Observe retrieval quality on mixed question types
* Ensure that irrelevant turns do not produce spurious retrieval
* Check if context is carried on in multi-turn conversation (does the AI remember and use all the information it was given to find the best chunk)

2) Batch 2 — Controlled Chunking Evaluation (called Batch_test_2_specific)

This batch is designed specifically to test chunk retrieval and specifically how performance varies across question types. There are 10 multi-turn dialogues were each 2 dialogues focus only around questions of a similar category. Every turn has a known ideal chunk.

The four categories are :

A) Recipe Questions — long, multi-section answers e.g. “How can I make chocolate chip cookies?”

B) Modification / Troubleshooting Questions — short, targeted fixes e.g “How can I make this gluten-free?”

C) Technical / Technique Questions — medium-length procedural skills e.g. “How do I temper chocolate?”

D) Conceptual / Scientific Questions — explanations of underlying principles e.g. “Explain the Maillard reaction.”

### Summary:
This evaluation setup lets us measure:

* How effectively each chunking method supports retrieval (quantitative)

* How chunking quality influences the model’s final answers (qualitative)

* How performance varies across question types

Together, these results indicate which chunking strategy is most suitable for a baking-themed RAG system.

# Quatitative Evaluation

## Setup and Chunking Method

In [ ]:
#Necessary Imports:
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_chroma import Chroma
import gradio as gr
from dotenv import load_dotenv
import json  
from datetime import datetime 
import os 
import json
from rouge_score import rouge_scorer
from collections import defaultdict
import pandas as pd
from langchain_openai import ChatOpenAI, OpenAIEmbeddings


#Loading google's api keya again from .env file
load_dotenv() 
DATA_PATH = r"data"
CHROMA_PATH = r"chroma_db"

#Loading the same embedding model used to create the chroma databases
embeddings_model = OpenAIEmbeddings(
    model="text-embedding-3-small"   
)

In [2]:
#Setting up the chroma database
#3 collections:
#cooking_chunks_fixed
#cooking_chunks_markdown
#cooking_chunks_semantic

#Run different collection names according to the one being tested
#Chunk_method ="cooking_chunks_fixed"
#Chunk_method ="cooking_chunks_markdown"
#Chunk_method ="cooking_chunks_semantic"

COLLECTION_NAME = "cooking_chunks_fixed"

vector_store = Chroma(
    collection_name=COLLECTION_NAME,
    embedding_function=embeddings_model,   
    persist_directory=CHROMA_PATH
)

In [3]:
########################### Defines all the helper methods needed to Evaluate ############


#This method retrieves the actual chunk bsaed on the id:
def get_chunk_text_by_id(chunk_id):
    """Retrieve actual chunk text from Chroma DB given the chunk_id."""
    res = vector_store.get(where={"chunk_id": int(chunk_id)})
    if res and res["documents"]:
        return res["documents"][0]
    return ""

#This method tokenises the input to allow token level comparison
def tokenize(text):
    return text.lower().replace("–", "-").replace("—", "-").split()


#This method calculate for a single golden chunk and the single retrieved chunk
##IOU
##F1
##Recall
##Precision
def token_overlap_metrics(gold, chunk):
    gold_tokens = set(tokenize(gold))
    chunk_tokens = set(tokenize(chunk))

    intersection = gold_tokens & chunk_tokens
    union = gold_tokens | chunk_tokens

    precision = len(intersection) / len(chunk_tokens) if chunk_tokens else 0
    recall = len(intersection) / len(gold_tokens) if gold_tokens else 0
    f1 = (2 * precision * recall) / (precision + recall) if precision + recall > 0 else 0
    iou = len(intersection) / len(union) if union else 0

    return precision, recall, f1, iou

#Defining Rouger_Scorere from the RougeScorer library 
scorer = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)

#The method returns the rouge_l for the gold/ideal chunk and the single retrieved chunk
def rouge_l_score(gold, chunk):
    """Return ROUGE-L F1 score."""
    score = scorer.score(gold.lower(), chunk.lower())
    return score["rougeL"].fmeasure

In [71]:
#This method takes in a JSON test file and outputs the metrics for each turn in the conversation
#How it deals with turns that don't have an ideal CHunk? 
# ->these ideal chunks are labelled NA and the method will skip them (not count them)

#How it deals with many chunks being retrieved for a single query (fixed size of 4 chunks)
# ->Finds the metrics for each retrieved chunk and gold chunk, and takes the single maximum values

#How it deal with the gold/ideal chunk being more than one?
# ->Finds the maximum values for both of those ideal chunks and averages them (measures if the whole system retrieved the best chunk)

#Note: slight bias as for recipe chunks, whole recipes take too much space to be one ideal chunk, so the ideal chunk for that was broken down into the recipies parts and treated as multiple chunks

def evaluate_from_json(json_path):
    """Runs Best-Match Multi-Gold evaluation and returns per-turn scores.
    Input: JSON multi-turn conversation test file (clearly labeled golden chunk and ideal response, see example file)
    Output: A JSON like format file with the metrics evaluated for each single turn in the conversation """

    #Open the JSON file
    with open(json_path, "r") as f:
        data = json.load(f)

    results = []

    #For each dialogue (dialog_idx) in the set of dialogues
    for dialog_idx, dialogue in enumerate(data, start=1):

        #Dataset sometimes stores turns as a flat list instead of {"turns": [...]}
        if isinstance(dialogue, dict) and "turns" in dialogue:
            turns = dialogue["turns"]
        else:
            turns = dialogue  #Already a list of turn dicts

            #for each turn within a dialogue
        for turn in turns:
            # Extract gold chunk(s)
            raw_gold = turn.get("ideal_chunk", "")

            #Handle NA or empty cases
            if isinstance(raw_gold, str):
                cleaned = raw_gold.strip()
                if cleaned == "" or cleaned.upper() == "NA":
                    continue
                gold_chunks = [cleaned]

            elif isinstance(raw_gold, list):
                gold_chunks = [g.strip() for g in raw_gold if g.strip() != ""]
                if len(gold_chunks) == 0:
                    continue
            else:
                continue
    
            #Retrieve the string of the chunks retrieved from Chroma
            retrieved_ids = [item["chunk_id"] for item in turn.get("retrieved_context", [])]

            retrieved_chunks = [
                get_chunk_text_by_id(cid)
                for cid in retrieved_ids
            ]

            #Compute Best-Match scores
            precision_scores = []
            recall_scores = []
            f1_scores = []
            iou_scores = []
            rougeL_scores = []

            #In cases were gold chunk is more than one
            for gold in gold_chunks:

                max_p = max_r = max_f = max_iou = max_rl = 0

                #Compare each retrieved chunk to one of the golden ones
                for chunk in retrieved_chunks:
                    #print("new chunk")
                    #print(chunk)
                    p, r, f1, iou = token_overlap_metrics(gold, chunk)
                    rl = rouge_l_score(gold, chunk)

                    max_p = max(max_p, p)
                    max_r = max(max_r, r)
                    max_f = max(max_f, f1)
                    max_iou = max(max_iou, iou)
                    max_rl = max(max_rl, rl)

                #Store best score for this gold
                precision_scores.append(max_p)
                recall_scores.append(max_r)
                f1_scores.append(max_f)
                iou_scores.append(max_iou)
                rougeL_scores.append(max_rl)

            #Average across gold chunks
            avg_precision = sum(precision_scores) / len(precision_scores)
            avg_recall    = sum(recall_scores)    / len(recall_scores)
            avg_f1        = sum(f1_scores)        / len(f1_scores)
            avg_iou       = sum(iou_scores)       / len(iou_scores)
            avg_rougeL    = sum(rougeL_scores)    / len(rougeL_scores)

            #Append per-turn result
            results.append({
                "dialogue_id": dialog_idx,
                "precision": avg_precision,
                "recall": avg_recall,
                "f1": avg_f1,
                "iou": avg_iou,
                "rouge_l": avg_rougeL
            })

    return results

In [73]:
#To test
result_for_each_turn = evaluate_from_json("Test_2_Fixed_results.json")
#See that the metrics will be returned for every turn in the conversation
result_for_each_turn

[{'dialogue_id': 1,
  'precision': 0.33088235294117646,
  'recall': 0.627906976744186,
  'f1': 0.43243243243243246,
  'iou': 0.305,
  'rouge_l': 0.38591852722287506},
 {'dialogue_id': 1,
  'precision': 0.5147058823529411,
  'recall': 0.9722222222222222,
  'f1': 0.6730769230769229,
  'iou': 0.5072463768115942,
  'rouge_l': 0.6805555555555556},
 {'dialogue_id': 1,
  'precision': 0.26229508196721313,
  'recall': 0.14035087719298245,
  'f1': 0.18285714285714283,
  'iou': 0.10062893081761007,
  'rouge_l': 0.1596958174904943},
 {'dialogue_id': 1,
  'precision': 1.0,
  'recall': 1.0,
  'f1': 1.0,
  'iou': 1.0,
  'rouge_l': 1.0},
 {'dialogue_id': 2,
  'precision': 0.6934865900383143,
  'recall': 0.7666666666666666,
  'f1': 0.6215078453884423,
  'iou': 0.46015325670498086,
  'rouge_l': 0.5649681022438328},
 {'dialogue_id': 2,
  'precision': 0.759493670886076,
  'recall': 1.0,
  'f1': 0.8633093525179857,
  'iou': 0.759493670886076,
  'rouge_l': 0.854054054054054},
 {'dialogue_id': 2,
  'precision': 0.3291139240506329,
  'recall': 0.16666666666666666,
  'f1': 0.22127659574468087,
  'iou': 0.12440191387559808,
  'rouge_l': 0.14933333333333332},
 {'dialogue_id': 3,
  'precision': 0.32894736842105265,
  'recall': 1.0,
  'f1': 0.4950495049504951,
  'iou': 0.32894736842105265,
  'rouge_l': 0.4078947368421052},
 {'dialogue_id': 3,
  'precision': 0.46938775510204084,
  'recall': 1.0,
  'f1': 0.6388888888888888,
  'iou': 0.46938775510204084,
  'rouge_l': 0.6391752577319588},
 {'dialogue_id': 3,
  'precision': 0.9866666666666667,
  'recall': 0.9345238095238095,
  'f1': 0.9591194968553459,
  'iou': 0.9244186046511628,
  'rouge_l': 0.977366255144033},
 {'dialogue_id': 3,
  'precision': 0.5,
  'recall': 1.0,
  'f1': 0.6666666666666666,
  'iou': 0.5,
  'rouge_l': 0.5875},
 {'dialogue_id': 3,
  'precision': 1.0,
  'recall': 1.0,
  'f1': 1.0,
  'iou': 1.0,
  'rouge_l': 1.0},
 {'dialogue_id': 4,
  'precision': 0.8961038961038961,
  'recall': 0.8518518518518519,
  'f1': 0.8734177215189873,
  'iou': 0.7752808988764045,
  'rouge_l': 0.776470588235294},
 {'dialogue_id': 4,
  'precision': 0.9875,
  'recall': 0.8586956521739131,
  'f1': 0.9186046511627908,
  'iou': 0.8494623655913979,
  'rouge_l': 0.8674698795180723},
 {'dialogue_id': 4,
  'precision': 0.953125,
  'recall': 0.7530864197530864,
  'f1': 0.8413793103448276,
  'iou': 0.7261904761904762,
  'rouge_l': 0.7586206896551724},
 {'dialogue_id': 5,
  'precision': 0.8895833333333334,
  'recall': 1.0,
  'f1': 0.941348117887365,
  'iou': 0.8895833333333334,
  'rouge_l': 0.9361387385118973},
 {'dialogue_id': 5,
  'precision': 0.75,
  'recall': 1.0,
  'f1': 0.8571428571428571,
  'iou': 0.75,
  'rouge_l': 0.8258064516129032},
 {'dialogue_id': 5,
  'precision': 0.5229591836734694,
  'recall': 1.0,
  'f1': 0.6431818181818182,
  'iou': 0.5229591836734694,
  'rouge_l': 0.6334072431633407},
 {'dialogue_id': 5,
  'precision': 0.6538461538461539,
  'recall': 1.0,
  'f1': 0.7906976744186047,
  'iou': 0.6538461538461539,
  'rouge_l': 0.8080808080808081},
 {'dialogue_id': 5,
  'precision': 0.85,
  'recall': 1.0,
  'f1': 0.9189189189189189,
  'iou': 0.85,
  'rouge_l': 0.9242424242424242},
 {'dialogue_id': 6,
  'precision': 0.6716417910447762,
  'recall': 1.0,
  'f1': 0.8035714285714287,
  'iou': 0.6716417910447762,
  'rouge_l': 0.7428571428571429},
 {'dialogue_id': 6,
  'precision': 0.4925373134328358,
  'recall': 0.7333333333333333,
  'f1': 0.5892857142857143,
  'iou': 0.4177215189873418,
  'rouge_l': 0.46896551724137925},
 {'dialogue_id': 6,
  'precision': 0.5,
  'recall': 1.0,
  'f1': 0.6666666666666666,
  'iou': 0.5,
  'rouge_l': 0.6226415094339622},
 {'dialogue_id': 6,
  'precision': 0.8723404255319149,
  'recall': 1.0,
  'f1': 0.9318181818181819,
  'iou': 0.8723404255319149,
  'rouge_l': 0.9444444444444444},
 {'dialogue_id': 7,
  'precision': 0.4444444444444444,
  'recall': 1.0,
  'f1': 0.6153846153846153,
  'iou': 0.4444444444444444,
  'rouge_l': 0.5920000000000001},
 {'dialogue_id': 7,
  'precision': 0.2569444444444444,
  'recall': 1.0,
  'f1': 0.40489596083231333,
  'iou': 0.2569444444444444,
  'rouge_l': 0.3444621091679915},
 {'dialogue_id': 7,
  'precision': 1.0,
  'recall': 1.0,
  'f1': 1.0,
  'iou': 1.0,
  'rouge_l': 1.0},
 {'dialogue_id': 7,
  'precision': 0.8727272727272727,
  'recall': 1.0,
  'f1': 0.9320388349514563,
  'iou': 0.8727272727272727,
  'rouge_l': 0.923076923076923},
 {'dialogue_id': 8,
  'precision': 0.671875,
  'recall': 1.0,
  'f1': 0.8037383177570093,
  'iou': 0.671875,
  'rouge_l': 0.7499999999999999},
 {'dialogue_id': 8,
  'precision': 0.8723404255319149,
  'recall': 1.0,
  'f1': 0.9318181818181819,
  'iou': 0.8723404255319149,
  'rouge_l': 0.9285714285714286},
 {'dialogue_id': 8,
  'precision': 0.5522388059701493,
  'recall': 1.0,
  'f1': 0.7115384615384616,
  'iou': 0.5522388059701493,
  'rouge_l': 0.7218045112781954},
 {'dialogue_id': 8,
  'precision': 0.4925373134328358,
  'recall': 1.0,
  'f1': 0.66,
  'iou': 0.4925373134328358,
  'rouge_l': 0.5950413223140496}]

In [74]:
#Saving the results
output_file = "metrics_for_every_single_turn.json"

with open(output_file, "w", encoding="utf-8") as f:
    json.dump(result_for_each_turn, f, indent=4)

In [75]:
#This Method takes the output of the previous cell/ JSON file containing the single turns
#and average per dialogue what the metrics are
#Outputs the average for each dialogue (divides each dialgoue by turns)


#Why not do this directly?
#->The earlier step is a good checker to debug; can clearly see the scores for each turn and inspect
#->Once you averaged the scores it difficult to see if the code is correctly calcualting the metrics and
#->Correctly skipped the NA dialogues 

def average_per_dialogue(results):
    """Compute averages of metrics for each dialogue.
    Input: JSON format of each metric for each turn
    Output: JSON format of each dialgoues average metrics"""
    grouped = defaultdict(list)

    # group all turns by dialogue ID
    for r in results:
        grouped[r["dialogue_id"]].append(r)

    dialogue_avgs = {}

    for d_id, turns in grouped.items():
        avg_precision = sum(t["precision"] for t in turns) / len(turns)
        avg_recall    = sum(t["recall"]    for t in turns) / len(turns)
        avg_f1        = sum(t["f1"]        for t in turns) / len(turns)
        avg_iou       = sum(t["iou"]       for t in turns) / len(turns)
        avg_rl        = sum(t["rouge_l"]   for t in turns) / len(turns)

        dialogue_avgs[d_id] = {
            "precision": avg_precision,
            "recall": avg_recall,
            "f1": avg_f1,
            "iou": avg_iou,
            "rouge_l": avg_rl
        }

    return dialogue_avgs

In [76]:
result_for_each_dialogue = average_per_dialogue(result_for_each_turn)
result_for_each_dialogue

{1: {'precision': 0.5269708293153327,
  'recall': 0.6851200190398476,
  'f1': 0.5720916245916245,
  'iou': 0.47821882690730105,
  'rouge_l': 0.5565424750672312},
 2: {'precision': 0.5940313949916743,
  'recall': 0.6444444444444445,
  'f1': 0.5686979312170363,
  'iou': 0.448016280488885,
  'rouge_l': 0.5227851632104067},
 3: {'precision': 0.657000358037952,
  'recall': 0.9869047619047618,
  'f1': 0.7519449114722793,
  'iou': 0.6445507456348513,
  'rouge_l': 0.7223872499436194},
 4: {'precision': 0.9455762987012987,
  'recall': 0.8212113079262838,
  'f1': 0.8778005610088685,
  'iou': 0.7836445802194262,
  'rouge_l': 0.8008537191361796},
 5: {'precision': 0.7332777341705914,
  'recall': 1.0,
  'f1': 0.8302578773099129,
  'iou': 0.7332777341705914,
  'rouge_l': 0.8255351331222747},
 6: {'precision': 0.6341298825023818,
  'recall': 0.9333333333333333,
  'f1': 0.747835497835498,
  'iou': 0.6154259338910082,
  'rouge_l': 0.6947271534942323},
 7: {'precision': 0.6435290404040404,
  'recall': 1.0,
  'f1': 0.7380798527920963,
  'iou': 0.6435290404040404,
  'rouge_l': 0.7148847580612286},
 8: {'precision': 0.647247886233725,
  'recall': 1.0,
  'f1': 0.7767737402784133,
  'iou': 0.647247886233725,
  'rouge_l': 0.7488543155409184}}

In [77]:
#Saving the results
output_file = "metrics_for_each_dialogue.json"

with open(output_file, "w", encoding="utf-8") as f:
    json.dump(result_for_each_dialogue, f, indent=4)

In [78]:
#This last method is the one that is most important
#The other two are still necessary for debugging and checking correct averaging
#This is what determines the overall average for that batch-replay script

#So having the two previous method is like a forced check that the code is correct
#IMPORTANT: the input here is the output of evaluate_from_json!!!! the other method average_per_dialogue is more of a checker function

def aggregate_overall_metrics(results):
    """Compute overall averages across all scored turns.
    Input: JSON file with metric results for each turn 
    Output: JSON file with average metrics for the whole batch replay script"""

    if not results: #in case it's empty/has no data
        print("ERROR wrong data type or no data is contained in the results")
        return None

    total = len(results)

    avg_precision = sum(r["precision"] for r in results) / total
    avg_recall    = sum(r["recall"]    for r in results) / total
    avg_f1        = sum(r["f1"]        for r in results) / total
    avg_iou       = sum(r["iou"]       for r in results) / total
    avg_rouge_l   = sum(r["rouge_l"]   for r in results) / total

    return {
        "total_turns_scored": total,
        "avg_precision": avg_precision,
        "avg_recall": avg_recall,
        "avg_f1": avg_f1,
        "avg_iou": avg_iou,
        "avg_rouge_l": avg_rouge_l
    }

In [79]:
results_overall = aggregate_overall_metrics(result_for_each_turn)
results_overall

{'total_turns_scored': 32,
 'avg_precision': 0.668053877998236,
 'avg_recall': 0.9001657648790224,
 'avg_f1': 0.7371760088306002,
 'avg_iou': 0.6288066165905138,
 'avg_rouge_l': 0.7053301053444895}

In [80]:
#Saving the results
output_file = "metrics_across_everything.json"

with open(output_file, "w", encoding="utf-8") as f:
    json.dump(results_overall, f, indent=4)

# Qualitative Metrics (LLM as a Judge)

In [158]:
#For LLM as a Judge these are the extra imports needed:
#Note it is important that the Judge LLM is more powerful and slightly different then the actually LLM
#Only this way can it accurately judge the response
from openai import OpenAI
#Loading api key from .env

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

In [159]:
#First we need to create the system prompt for the LLM judge

#The judge will have acess to the history of the conversation, the users query, the LLM response, the ideal response, and the ideal chunk
def build_judge_prompt(history, user, response, ground_truth, ideal_chunk):
    """
    Builds the LLM-as-a-Judge prompt to evaluate an assistant response using:
    - Factual Accuracy
    - Helpfulness
    - Groundedness (if an ideal chunk exists)
    """

    #Converts dialogue history to readable text for the LLM judge
    history_text = ""
    for h in history:
        history_text += f"{h['role'].capitalize()}: {h['content']}\n"

    #Base prompt that applies to all cases
    base_prompt = f"""
You are an impartial evaluation model. Your task is to evaluate the assistant’s answer 
using **three metrics**. You MUST follow the comparison rules for each metric exactly.

The domain of this system is *baking*. 
If the question is not about baking (e.g., greetings or mistakes), evaluate the metrics 
logically given the information provided.

METRIC DEFINITIONS AND REQUIRED REFERENCES:
1. **Factual Accuracy (1–5):**
   Compare ONLY:
       - the assistant's response
       - the ground-truth answer
   Rate how correct, precise, and non-hallucinatory the assistant's answer is.
   Ignore the ideal chunk when scoring accuracy. Did the response use the exact same value and metrics as the ground-truth answer?

2. **Helpfulness (1–5):**
   Compare ONLY:
       - the user’s question
       - the assistant’s response
   Rate how useful, actionable, and responsive the answer is to the user’s intent.
   An answer can be factually correct but still unhelpful, or vice versa.

3. **Groundedness (1–5 or "N/A"):**
   ONLY evaluate if an ideal chunk is provided.
   Compare ONLY:
       - the assistant's response
       - the ideal knowledge chunk
   Rate how well the answer is supported by that chunk.
   If no chunk exists (ideal_chunk == "NA"), groundedness must be "N/A".


Return ONLY a JSON object with these fields and numeric scores.
DIALOGUE HISTORY
{history_text}

CURRENT TURN
User question:
{user}

Assistant response:
{response}

Ground-truth answer (used ONLY for factual accuracy):
{ground_truth}
"""

    # If ideal chunk exists, evaluate groundedness normally
    if ideal_chunk and ideal_chunk.strip().upper() != "NA":
        base_prompt += f"""
Ideal (gold) chunk (used ONLY for groundedness):
{ideal_chunk}

Return JSON exactly in this format:
{{
 "factual_accuracy": <1-5>,
 "helpfulness": <1-5>,
 "groundedness": <1-5>
}}
"""
    #If no ideal chunk exists then can't evaluate groundesnes; groundedness = N/A
    else:
        base_prompt += """
No ideal chunk is provided for this turn.

Return JSON exactly in this format:
{
 "factual_accuracy": <1-5>,
 "helpfulness": <1-5>,
 "groundedness": "N/A"
}
"""

    return base_prompt

In [160]:
#This is the method that runs the LLM judge with the prompt given above

#The model used as the judge is specified as model
#This case we used gpt-4o-mini because it is stronger than gpt-5-nano but still cheap (limited credits)
#This evaluation file will be outputed as a json file inside the project folder

def judge_batch_file(json_path, output_path="LLM_judge_scores.json", model="gpt-4o-mini"):
    """
    Evaluates every turn in a batch replay JSON file using LLM-as-a-Judge.
    Input: JSON_path of where the batch replay script to evaluate is.
    Output: produces a JSON file with per-turn ratings.
    """

    #Open's the recorded test conversation JSON file (this get created in the Notebook chatbot_interface)
    with open(json_path, "r") as f:
        dialogues = json.load(f)

    #List to store all results
    all_results = []

    #for each dialogue within all the dialogues
    for dialogue in dialogues:
        history = []

        #for each turn within a single dialogue 
        for turn in dialogue["turns"]:

            #records information from the JSON file to give the LLM as a judge
            user = turn["user_utterance"]
            system_response = turn["system_response"]
            ground_truth = turn["ground_truth"]
            raw_ideal_chunk = turn.get("ideal_chunk", "NA")

            #These are the tests necessary for what gets retrived from ideal_chunk
            #In cases were the chunk does not exist:
            if raw_ideal_chunk == "NA" or raw_ideal_chunk is None:
                ideal_chunk = "NA"

            #In cases were the chunk exists as a string:
            elif isinstance(raw_ideal_chunk, str):
                ideal_chunk = raw_ideal_chunk

            #In cases were there are multiple chunks/list, then store them all mergwed
            elif isinstance(raw_ideal_chunk, list):
                ideal_chunk = "\n\n".join(raw_ideal_chunk)
            #Last case, if the format is something else/unexpect from the previous ones
            else:
                ideal_chunk = str(raw_ideal_chunk)

            #Builds judge prompt from before with that infromation
            prompt = build_judge_prompt(
                history=history,
                user=user,
                response=system_response,
                ground_truth=ground_truth,
                ideal_chunk=ideal_chunk
            )

            #Calls OPENAi model and passes it the prompt
            judge_output = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": "You are an impartial evaluation model."},
                    {"role": "user", "content": prompt}
                ]
            )

            raw_json = judge_output.choices[0].message.content

            #Gets scores returned from the Judge
            try:
                scores = json.loads(raw_json)
            except:
                print("ERROR PARSING JUDGE OUTPUT:", raw_json)
                continue

            #Saves those scores as a JSON file to add to the bigger list
            result = {
                "dialogue_id": dialogue["dialogue_id"],
                "user_utterance": user,
                "system_response": system_response,
                "ground_truth": ground_truth,
                "ideal_chunk": ideal_chunk,
                "scores": scores,
                "timestamp": datetime.now().isoformat() + "Z"
            }

            all_results.append(result)

            #Update history for next turn (just for that dialogue, then history get cleared for next dialogue, no contamination)
            history.append({"role": "user", "content": user})
            history.append({"role": "assistant", "content": system_response})

    #Save results
    with open(output_path, "w") as f:
        json.dump(all_results, f, indent=4)

    print(f"Saved judge scores to {output_path}")
    return all_results

In [161]:
results_llm = judge_batch_file("semantic_test_2_del.json")
results_llm

Saved judge scores to LLM_judge_scores.json

[{'dialogue_id': 1,
  'user_utterance': 'Do you know any cookie recipes? Just give me an overview of the ones you know?',
  'system_response': 'Sure — here’s what I have in my baking knowledge base about cookies:\n\nCookie recipe in the knowledge base\n- Chewy Almond Cookies\n  - 4 ingredients, oil-free, and naturally gluten-free almond cookies\n  - Ingredients:\n    - Almond flour\n    - Granulated sugar\n    - Eggs\n    - Natural almond extract\n    - A pinch of salt\n  - Instructions (summary of steps as listed):\n    1) Preheat oven to 350°F (325°F convection). Line 1–2 baking trays with parchment.\n    2) In a large bowl, mix together eggs, sugar, and almond extract.\n    3) Add almond flour and salt; mix with a spoon or spatula.\n    4) Form into 1 tbsp dough mounds, roll into balls, and place on baking sheet 1–2" apart. Decorate with a few sliced almonds.\n    5) Bake for 15–17 minutes, or until the tops are dry to the touch and the edges/bottom are golden brown.\n    6) Let cool on the baking sheet.\n    7) Dust with powdered sugar and store in an airtight container at room temperature for 3–5 days or in the freezer for up to 6 months. Enjoy!\n\nGeneral cookie tips and factors from the knowledge base\n- Texture and crispness:\n  - Most crisp cookies are made from a stiff dough.\n  - Crispness can be influenced by how much sugar and fat you use, how long you bake, and how you store cookies.\n  - Convection ovens dry cookies faster, contributing to crispness.\n  - Small or thin cookies dry faster during baking.\n  - Proper storage can affect whether cookies stay crisp.\n- Cookie spread and dough behavior:\n  - Spread is influenced by sugar content: high sugar increases spread; coarse sugar increases spread, while fine sugar or confectioners’ sugar reduces spread.\n  - High baking soda or baking ammonia encourages spread.\n  - Creaming fat and sugar adds air and contributes to leavening and spread; blending fat and sugar just to a paste (without creaming) reduces spread.\n  - Low oven temperature increases spread; high temperature decreases spread because the cookie sets up faster.\n  - A slack batter (more liquid) spreads more than a stiff dough.\n  - Strong flour or activation of gluten decreases spread.\n  - Cookies tend to spread more when baked on heavily greased pans.\n\nIf you’d like, I can pull out more cookie-related ideas that fit within these notes, or focus on a specific cookie texture (chewy, crisp, soft) using only the information provided.',
  'ground_truth': 'Yes! I have a few. You can try chewy chocolate chip cookies, or make simple 4-ingredient chewy almond cookies both are delicious and easy to prepare.',
  'ideal_chunk': "# Recipe chocolate chip cookies\nDelicious chewy chocolate chip cookies that don't require chilling, and are perfectly soft, chewy and crunchy at the same time!\nPrep Time: 20minutes minutesCook Time: 24minutes minutesCooling Time: 30minutes minutesTotal Time: 1hour hour 14minutes minutes Servings: 20 cookies\n\n# Recipe Chewy Almond Cookies\nThese Chewy Almond Cookies are so good they are passed down for generations and leave everyone who tries them craving more! You will be amazed at how delicious this 4 ingredient, oil-free, and naturally gluten-free, almond cookie recipe is!\nPrep Time 5 minutes \nCook Time 15 minutes ",
  'scores': {'factual_accuracy': 3, 'helpfulness': 4, 'groundedness': 2},
  'timestamp': '2025-12-08T18:38:42.587187Z'},
 {'dialogue_id': 1,
  'user_utterance': 'What ingredients do I need for chocolate chip cookies?',
  'system_response': 'Here are the ingredients for chocolate chip cookies from the knowledge base:\n\n- 175 g unsalted butter\n- 225 g light brown soft sugar\n- 100 g white granulated sugar\n- 1 tsp vanilla extract\n- 1 medium egg\n- 1 egg yolk\n- 275 g plain flour\n- 1/2 tsp bicarbonate of soda\n- 1/2 tsp sea salt\n- 325 g chocolate chips',
  'ground_truth': 'Here are the ingredients for Delicious chewy chocolate chip cookies: Ingredients\n175 g unsalted butter\n225 g light brown soft sugar\n100 g white granulated sugar\n1 tsp vanilla extract\n1 medium egg\n1 egg yolk\n275 g plain flour\n1/2 tsp bicarbonate of soda\n1/2 tsp sea salt\n325 g chocolate chips',
  'ideal_chunk': '"# Recipe chocolate chip cookies Ingredients\n175 g unsalted butter\n225 g light brown soft sugar\n100 g white granulated sugar\n1 tsp vanilla extract\n1 medium egg\n1 egg yolk\n275 g plain flour\n1/2 tsp bicarbonate of soda\n1/2 tsp sea salt\n325 g chocolate chips',
  'scores': {'factual_accuracy': 5, 'helpfulness': 5, 'groundedness': 5},
  'timestamp': '2025-12-08T18:38:43.534049Z'},
 {'dialogue_id': 1,
  'user_utterance': 'What steps or the method needed to make them?',
  'system_response': 'From the knowledge base, the chocolate chip cookies method includes:\n- 1) Preheat the oven to 190°C / 170°C Fan and line 2 large baking trays with parchment paper.\n- 2) Melt the butter slowly until it is fully melted, leave to cool for a couple of minutes.\n\nThe remaining steps are not present in the knowledge base.',
  'ground_truth': 'Here are the steps: \nPreheat the oven to 190ºC/170ºC Fan and Line 2 Large baking trays with parchment paper.\nMelt the butter slowly until it is fully melted, leave to cool for a couple of minutes.\nOnce cooled, beat in both the light brown soft sugar and granulated sugar until they are all thoroughly combined.\nAdd the egg, egg yolk and vanilla extract and beat the mixture until the mixture becomes much lighter in colour, is smooth, and has increased in volume.\nAdd the dry ingredients (plain flour, bicarbonate of soda, and sea salt) and beat again until smooth.\nFold through the chocolate chips.\nUsing a 5cm Scoop, portion the cookies onto the trays (I did 6 per tray).\nBake the cookies in the oven for 12-13 minutes for softer chewy cookies, OR 15 minutes for soft/crunchy cookies.\nLeave the cookies on the tray for 5 minutes after they have finished baking, and then transfer to a wire rack and continue to cool! Enjoy! ',
  'ideal_chunk': '# Recipe chocolate chip cookies Methods\nInstructions\nPreheat the oven to 190ºC/170ºC Fan and Line 2 Large baking trays with parchment paper.\nMelt the butter slowly until it is fully melted, leave to cool for a couple of minutes.\nOnce cooled, beat in both the light brown soft sugar and granulated sugar until they are all thoroughly combined.\nAdd the egg, egg yolk and vanilla extract and beat the mixture until the mixture becomes much lighter in colour, is smooth, and has increased in volume.\nAdd the dry ingredients (plain flour, bicarbonate of soda, and sea salt) and beat again until smooth.\nFold through the chocolate chips.\nUsing a 5cm Scoop, portion the cookies onto the trays (I did 6 per tray).\nBake the cookies in the oven for 12-13 minutes for softer chewy cookies, OR 15 minutes for soft/crunchy cookies.\nLeave the cookies on the tray for 5 minutes after they have finished baking, and then transfer to a wire rack and continue to cool! Enjoy!',
  'scores': {'factual_accuracy': 3, 'helpfulness': 3, 'groundedness': 3},
  'timestamp': '2025-12-08T18:38:44.429412Z'},
 {'dialogue_id': 1,
  'user_utterance': 'Are there any troubleshoots or notes I should be aware of?',
  'system_response': 'Here are the troubleshooting notes from the Cookies Troubleshoot section:\n\n- Crispness\n  - Cookies are crisp when they are low in moisture. Factors that affect crispness include the amount of sugar and fat, how long you bake, and how you store cookies.\n  - Convection ovens dry cookies faster, contributing to crispness.\n  - Small or thin cookies dry faster during baking.\n  - Proper storage can affect whether cookies stay crisp.\n\n- How to fix crispness\n  - Bake on the correct temperature. Use an oven thermometer to ensure your oven is at the exact right temperature.\n  - Measure ingredients using kitchen scales.\n\n- Spread and dough behavior\n  - Spread is influenced by sugar content: high sugar increases spread; coarse sugar increases spread, while fine sugar or confectioners’ sugar reduces spread.\n  - High baking soda or baking ammonia encourages spread.\n  - Creaming fat and sugar adds air and contributes to leavening and spread; blending fat and sugar just to a paste (without creaming) reduces spread.\n  - Low oven temperature increases spread; high temperature decreases spread because the cookie sets up faster.\n  - A slack batter (more liquid) spreads more than a stiff dough.\n  - Strong flour or activation of gluten decreases spread.\n  - Cookies tend to spread more when baked on heavily greased pans.\n\n- If you’d like, I can pull out more cookie-related ideas that fit within these notes, or focus on a specific cookie texture (chewy, crisp, soft) using only the information provided.',
  'ground_truth': 'Yes! When baking cookies, it helps to start checking them at the minimum baking time so they don’t overcook or burn. If you like softer cookies, take them out right at the minimum time. If you prefer them more browned with slightly crisp edges, leave them in a little longer. Once they’ve cooled, you can store them in an airtight container at room temperature for about 5 days.',
  'ideal_chunk': '# Recipe chocolate chip cookies Notes Troubleshoot\nListen to your intuition when baking. Start checking on your cookies at the minimum baking time to ensure you don’t overcook or even burn them. If you prefer soft cookies, cook only to the minimum time. If you prefer your cookies to be browned with slightly crisp edges, cook a little longer.\nStoring: In general, cooled cookies can be stored in an airtight container at room temperature for about 5 days.\n',
  'scores': {'factual_accuracy': 2, 'helpfulness': 3, 'groundedness': 2},
  'timestamp': '2025-12-08T18:38:45.455050Z'},
 {'dialogue_id': 2,
  'user_utterance': 'Give me the full recipe, step by step, to bake an angel cake?',
  'system_response': 'Here is the angel food cake recipe as provided:\n\nIngredients\n- 1 and 3/4 cups (350g) granulated sugar\n- 1 cup + 2 Tablespoons (133g) cake flour\n- 1/4 teaspoon salt\n- 12 large egg whites, at room temperature\n- 1 and 1/2 teaspoons cream of tartar\n- 1 and 1/2 teaspoons pure vanilla extract\n- Optional: confectioners’ sugar for dusting, whipped cream, and berries\n\nInstructions\n1) Adjust the oven rack to the lower middle position and preheat to 325°F (163°C). In a food processor or blender, pulse the sugar until fine and powdery.\n\n2) Remove 1 cup and set aside to use in step 3; keep the rest inside the food processor. Add the cake flour and salt to the food processor. Pulse 5-10 times until sugar/flour/salt mixture is aerated and light.\n\n3) In a large bowl using a hand mixer or a stand mixer fitted with a whisk attachment, whip egg whites and cream of tartar together on medium-low until foamy, about 1 minute. Switch to medium-high and slowly add the 1 cup of sugar you set aside. Whip until soft peaks form, about 5-6 minutes. Add the vanilla extract, then beat just until incorporated.\n\n4) In 3 additions, slowly sift the flour mixture into the egg white mixture using a fine mesh strainer, gently folding with a rubber spatula after each addition. To avoid deflating or a dense cake, don’t add the flour mixture all at once. Sift and very slowly fold in several additions. This is important!\n\n5) Pour and spread batter into an ungreased 9 or 10 inch tube pan. Shimmy the pan on the counter to smooth down the surface.\n\n6) Bake the cake until a toothpick inserted comes out clean, about 40-45 minutes. Rotate the pan halfway through baking.\n\n7) The cake will rise up very tall while baking. Remove from the oven, then cool the cake completely upside-down set on a wire rack, about 3 hours. (Upside-down so the bottom of the tube pan is right-side up, see photo and video above.)\n\n8) Once cooled, run a thin knife around the edges and gently tap the pan on the counter until the cake releases. If desired, dust with confectioners’ sugar.',
  'ground_truth': 'Sure. Here are the ingredients for a perfect angel food cake bakes up tall, light, and airy. Time: 40 minutes. Total Time: 4 hours  Yield: serves 10-12 # Angel Food Cake Ingredients\nIngredients\n1 and 3/4 cups (350g) granulated sugar*\n1 cup + 2 Tablespoons (133g) cake flour (spooned & leveled)\n1/4 teaspoon salt\n12 large egg whites, at room temperature*\n1 and 1/2 teaspoons cream of tartar\n1 and 1/2 teaspoons pure vanilla extract\noptional: confectioners’ sugar for dusting, whipped cream, and berries \nInstructions\nAdjust the oven rack to the lower middle position and preheat oven to 325°F (163°C).\n\nIn a food processor or blender, pulse the sugar until fine and powdery. Remove 1 cup and set aside to use in step 3; keep the rest inside the food processor. Add the cake flour and salt to the food processor. Pulse 5-10 times until sugar/flour/salt mixture is aerated and light.\nIn a large bowl using a hand mixer or a stand mixer fitted with a whisk attachment, whip egg whites and cream of tartar together on medium-low until foamy, about 1 minute. Switch to medium-high and slowly add the 1 cup of sugar you set aside. Whip until soft peaks form, about 5-6 minutes. See photo and video above for a visual. Add the vanilla extract, then beat just until incorporated.\nIn 3 additions, slowly sift the flour mixture into the egg white mixture using a fine mesh strainer, gently folding with a rubber spatula after each addition. To avoid deflating or a dense cake, don’t add the flour mixture all at once. Sift and very slowly fold in several additions. This is important! Pour and spread batter into an ungreased 9 or 10 inch tube pan. Shimmy the pan on the counter to smooth down the surface.\n\nBake the cake until a toothpick inserted comes out clean, about 40-45 minutes. Rotate the pan halfway through baking. The cake will rise up very tall while baking. Remove from the oven, then cool the cake completely upside-down set on a wire rack, about 3 hours. (Upside-down so the bottom of the tube pan is right-side up, see photo and video above.) Once cooled, run a thin knife around the edges and gently tap the pan on the counter until the cake releases.\nIf desired, dust with confectioners’ sugar. Slice the cake with a sharp serrated knife. Regular knives can easily squish the cake. Serve with whipped cream and fresh berries.\nStore leftovers in the refrigerator for up to 5 days.',
  'ideal_chunk': '# Angel Food Cake Recipe\nUsing only 6 ingredients, this perfect angel food cake bakes up tall, light, and airy. For best results, read the recipe in full before beginning and have all your ingredients ready to go. Enjoy! Prep Time: 25 minutes  Cook Time: 40 minutes. Total Time: 4 hours  Yield: serves 10-12\n\n# Angel Food Cake Ingredients\nIngredients\n1 and 3/4 cups (350g) granulated sugar*\n1 cup + 2 Tablespoons (133g) cake flour (spooned & leveled)\n1/4 teaspoon salt\n12 large egg whites, at room temperature*\n1 and 1/2 teaspoons cream of tartar\n1 and 1/2 teaspoons pure vanilla extract\noptional: confectioners’ sugar for dusting, whipped cream, and berries\n\n# Angel Food Cake Instructions\nInstructions\nAdjust the oven rack to the lower middle position and preheat oven to 325°F (163°C).\n\nIn a food processor or blender, pulse the sugar until fine and powdery. Remove 1 cup and set aside to use in step 3; keep the rest inside the food processor. Add the cake flour and salt to the food processor. Pulse 5-10 times until sugar/flour/salt mixture is aerated and light.\nIn a large bowl using a hand mixer or a stand mixer fitted with a whisk attachment, whip egg whites and cream of tartar together on medium-low until foamy, about 1 minute. Switch to medium-high and slowly add the 1 cup of sugar you set aside. Whip until soft peaks form, about 5-6 minutes. See photo and video above for a visual. Add the vanilla extract, then beat just until incorporated.\nIn 3 additions, slowly sift the flour mixture into the egg white mixture using a fine mesh strainer, gently folding with a rubber spatula after each addition. To avoid deflating or a dense cake, don’t add the flour mixture all at once. Sift and very slowly fold in several additions. This is important! Pour and spread batter into an ungreased 9 or 10 inch tube pan. Shimmy the pan on the counter to smooth down the surface.\n\nBake the cake until a toothpick inserted comes out clean, about 40-45 minutes. Rotate the pan halfway through baking. The cake will rise up very tall while baking. Remove from the oven, then cool the cake completely upside-down set on a wire rack, about 3 hours. (Upside-down so the bottom of the tube pan is right-side up, see photo and video above.) Once cooled, run a thin knife around the edges and gently tap the pan on the counter until the cake releases.\nIf desired, dust with confectioners’ sugar. Slice the cake with a sharp serrated knife. Regular knives can easily squish the cake. Serve with whipped cream and fresh berries.\nStore leftovers in the refrigerator for up to 5 days.',
  'scores': {'factual_accuracy': 5, 'helpfulness': 5, 'groundedness': 5},
  'timestamp': '2025-12-08T18:38:46.785380Z'},
 {'dialogue_id': 2,
  'user_utterance': 'Actually I don’t think I have those ingredients. Can I make a caramel cake instead? What are the Ingredients?',
  'system_response': 'Here are the ingredients for the Easy caramel cake from the knowledge base:\n\nCake\n- 225 g softened salted butter, plus extra for the tins\n- 125 g golden caster sugar\n- 100 g light brown soft sugar\n- 1 tsp vanilla extract\n- 4 large eggs\n- 225 g self raising flour\n- 2 tbsp milk\n- toffee\n- chocolate or caramel pieces, to decorate\n\nIcing\n- 200 g softened salted butter\n- 400 g icing sugar (golden icing sugar if you can find it – it adds a golden colour and caramel flavour)\n- 70 g caramel sauce\n- dulce de leche or caramel spread, plus 3 tbsp to serve',
  'ground_truth': 'Yes, ofcourse! These are the ingredients for the caramel cake: \n 225g softened salted butter\nplus extra for the tins\n125g golden caster sugar\n100g light brown soft sugar\n1 tsp vanilla extract\n4 large eggs\n225g self raising flour\n2 tbsp milk\ntoffee\nchocolate or caramel pieces, to decorate\nFor the icing\n200g softened salted butter\n400g icing sugar\n(golden icing sugar if you can find it – it adds a golden colour and caramel flavour)\n70g caramel sauce\ndulce de leche or caramel spread, plus 3 tbsp to serve',
  'ideal_chunk': '225g softened salted butter\nplus extra for the tins\n125g golden caster sugar\n100g light brown soft sugar\n1 tsp vanilla extract\n4 large eggs\n225g self raising flour\n2 tbsp milk\ntoffee\nchocolate or caramel pieces, to decorate\nFor the icing\n200g softened salted butter\n400g icing sugar\n(golden icing sugar if you can find it – it adds a golden colour and caramel flavour)\n70g caramel sauce\ndulce de leche or caramel spread, plus 3 tbsp to serve',
  'scores': {'factual_accuracy': 5, 'helpfulness': 5, 'groundedness': 5},
  'timestamp': '2025-12-08T18:38:48.014249Z'},
 {'dialogue_id': 2,
  'user_utterance': 'Great! I should have all those things, tell me step by step how to make it?',

In [162]:
#Saving the results
output_file = "LLM_judge_full_output.json"

with open(output_file, "w", encoding="utf-8") as f:
    json.dump(results_llm, f, indent=4)

In [163]:
df = pd.DataFrame(results_llm)
df

,dialogue_id,user_utterance,system_response,ground_truth,ideal_chunk,scores,timestamp
0,1,Do you know any cookie recipes? Just give me a...,Sure — here’s what I have in my baking knowled...,Yes! I have a few. You can try chewy chocolate...,# Recipe chocolate chip cookies\nDelicious che...,"{'factual_accuracy': 3, 'helpfulness': 4, 'gro...",2025-12-08T18:38:42.587187Z
1,1,What ingredients do I need for chocolate chip ...,Here are the ingredients for chocolate chip co...,Here are the ingredients for Delicious chewy c...,"""# Recipe chocolate chip cookies Ingredients\n...","{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:38:43.534049Z
2,1,What steps or the method needed to make them?,"From the knowledge base, the chocolate chip co...",Here are the steps: \nPreheat the oven to 190º...,# Recipe chocolate chip cookies Methods\nInstr...,"{'factual_accuracy': 3, 'helpfulness': 3, 'gro...",2025-12-08T18:38:44.429412Z
3,1,Are there any troubleshoots or notes I should ...,Here are the troubleshooting notes from the Co...,"Yes! When baking cookies, it helps to start ch...",# Recipe chocolate chip cookies Notes Troubles...,"{'factual_accuracy': 2, 'helpfulness': 3, 'gro...",2025-12-08T18:38:45.455050Z
4,2,"Give me the full recipe, step by step, to bake...",Here is the angel food cake recipe as provided...,Sure. Here are the ingredients for a perfect a...,# Angel Food Cake Recipe\nUsing only 6 ingredi...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:38:46.785380Z
5,2,Actually I don’t think I have those ingredient...,Here are the ingredients for the Easy caramel ...,"Yes, ofcourse! These are the ingredients for t...",225g softened salted butter\nplus extra for th...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:38:48.014249Z
6,2,"Great! I should have all those things, tell me...",Here are the Easy caramel cake ingredients and...,Here are the steps: \n1) Heat the oven to 180C...,## Easy caramel cake Method\n1) Heat the oven ...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:38:49.138466Z
7,3,Give me the ingredients to a lemon drizzle cak...,Lemon drizzle cake ingredients:\n\n- 225g unsa...,Here are the ingredients for a lemon drizzle c...,# Recipe Lemon drizzle cake Ingredients\n225g ...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:38:50.266012Z
8,3,Can I make this recipe gluten free? How?,Yes. To make this lemon drizzle cake gluten-fr...,"Yes, simply replace the self-raising flour wit...","To make this lemon drizzle cake gluten-free, s...","{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:38:52.753674Z
9,3,I don’t have eggs can I still make this recipe...,- For the lemon drizzle cake: Eggs are essenti...,Unfortunately no. Eggs play a crucial role as ...,Eggs play a crucial role in this lemon drizzle...,"{'factual_accuracy': 4, 'helpfulness': 5, 'gro...",2025-12-08T18:38:53.773821Z
10,3,"Okay, let's make Gluten-Free Vegan Lemon pie. ...",Yes. The Gluten-Free Vegan Lemon Pie can use a...,"Yes, although almond will make it less creamy ...","You can use any type of plant-based milk, thou...","{'factual_accuracy': 5, 'helpfulness': 4, 'gro...",2025-12-08T18:38:55.079147Z
11,3,"I ran out of maple syrup, does honey work?",Yes. Honey can be used as a substitute for map...,"Yes, as the recipe says any other sweetener wo...","If you don’t have maple syrup on hand, feel fr...","{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:38:56.205147Z
12,4,Explain only why my macarons crack in the oven?,"- They weren’t left to dry long enough, so the...",Macarons usually crack when the shells don’t f...,Macarons where not left to dry long enough. Th...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:38:57.229563Z
13,4,Explain how can I fix it?,Here are the fixes listed in my baking guidanc...,The best way to prevent cracked macarons is to...,Make sure you let your macarons rest long enou...,"{'factual_accuracy': 4, 'helpfulness': 4, 'gro...",2025-12-08T18:38:58.253136Z
14,4,Why are my macarons brown after baking? How ca...,- Why it happens:\n - Baking on too high a te...,Macarons usually turn brown when the oven temp...,Why it happened\nBaking on too high a temperat...,"{'factual_accuracy': 4, 'helpfulness': 5, 'gro...",2025-12-08T18:38:59.276616Z
15,5,What is the art of chocolate tempering? And wh...,Here’s what the knowledge says about chocolate...,The art of chocolate tempering is the careful ...,Tempering chocolate is one of the foundational...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:00.402740Z
16,5,Why do I have to cool it all the way down and ...,Tempering is meant to shape the chocolate’s co...,Cooling the chocolate all the way down and the...,"To encourage this stable crystal form, chocola...","{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:01.325231Z
17,5,Do different chocolates use the same temperatu...,Not exactly. Different chocolates use differen...,Different chocolates do not use the same tempe...,Each variety contains different ratios of coco...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:02.348960Z
18,5,There are unmelted lumps in my chocolate now t...,Unmelted lumps can happen as chocolate cools. ...,Lumps usually appear when the chocolate wasn’t...,"Occasionally, as chocolate cools, unmelted lum...","{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:03.782771Z
19,5,Why did my chocolate turn thick and grainy?,Grainy and thick chocolate is often due to sei...,Chocolate turns thick and grainy when it overh...,"If the chocolate becomes thick, grainy, or une...","{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:04.910659Z
20,6,I’m trying to understand how long I should kne...,The knowledge I have doesn’t give a exact knea...,You’ll know your dough is sufficiently kneaded...,Dough that has been kneaded enough becomes smo...,"{'factual_accuracy': 3, 'helpfulness': 4, 'gro...",2025-12-08T18:39:05.933467Z
21,6,What exactly is the windowpane test?,The windowpane test is a method to check glute...,It’s a simple check where you stretch a small ...,One of the most reliable ways bakers evaluate ...,"{'factual_accuracy': 4, 'helpfulness': 5, 'gro...",2025-12-08T18:39:07.266442Z
22,6,And what happens if I knead too much?,"If you knead too much, the dough can become ov...","Over-kneading makes the dough tight, stiff, an...",kneading for too long can have the opposite ef...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:08.492842Z
23,6,"Okay, that makes sense. Should the dough still...",Yes. A well-kneaded dough doesn’t have to be c...,"Yes, properly kneaded dough can still feel sli...",Well-kneaded dough doesn’t have to be complete...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:09.824136Z
24,7,Why do cookies turn golden brown in the oven? ...,Cookies turn golden brown mainly because of he...,Cookies turn golden because heat triggers a re...,One of the most important of these is the Mail...,"{'factual_accuracy': 4, 'helpfulness': 5, 'gro...",2025-12-08T18:39:11.406932Z
25,7,So is it the same thing as caramelization?,Not exactly. Browning in cookies comes from tw...,"Caramelization contributes to browning, but it...","Caramelization also plays a part, though it wo...","{'factual_accuracy': 4, 'helpfulness': 5, 'gro...",2025-12-08T18:39:12.272740Z
26,7,Is there a way to increase browning if my cook...,Yes. Browning is driven by Maillard reactions ...,You can increase browning in your cookies by e...,Maillard browning is influenced by temperature...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:13.410520Z
27,7,That’s interesting. Does this reaction happen ...,Yes. This browning happens in bread too—the cr...,"Yes, bread develops its crust through the same...",This browning process extends far beyond cooki...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:14.329802Z
28,8,What is Egg Coagulation in Baking?,"Egg coagulation is the process where, when egg...",Egg coagulation is the process where egg prote...,"When eggs are heated, their proteins unfold an...","{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:15.865941Z
29,8,What is Gelatinization of Starch in Baking?,Gelatinization is how starch behaves when heat...,Gelatinization happens when starch granules he...,As starch granules heat in the presence of moi...,"{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:16.760445Z
30,8,Why does whipping egg whites make them so stiff?,"Whipping egg whites introduces air, and the pr...",Whipping egg whites traps air and causes their...,"Whipping egg whites introduces air, allowing p...","{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:17.913455Z
31,8,Why does over whipping them change them?,Whipping egg whites traps air and the egg whit...,"When egg whites are whipped too long, the prot...","if beaten for too long, the network becomes ov...","{'factual_accuracy': 5, 'helpfulness': 5, 'gro...",2025-12-08T18:39:19.039906Z

In [164]:
scores_df = df["scores"].apply(pd.Series)
df_expanded = pd.concat([df.drop(columns=["scores"]), scores_df], axis=1)
df_expanded

,dialogue_id,user_utterance,system_response,ground_truth,ideal_chunk,timestamp,factual_accuracy,helpfulness,groundedness
0,1,Do you know any cookie recipes? Just give me a...,Sure — here’s what I have in my baking knowled...,Yes! I have a few. You can try chewy chocolate...,# Recipe chocolate chip cookies\nDelicious che...,2025-12-08T18:38:42.587187Z,3,4,2
1,1,What ingredients do I need for chocolate chip ...,Here are the ingredients for chocolate chip co...,Here are the ingredients for Delicious chewy c...,"""# Recipe chocolate chip cookies Ingredients\n...",2025-12-08T18:38:43.534049Z,5,5,5
2,1,What steps or the method needed to make them?,"From the knowledge base, the chocolate chip co...",Here are the steps: \nPreheat the oven to 190º...,# Recipe chocolate chip cookies Methods\nInstr...,2025-12-08T18:38:44.429412Z,3,3,3
3,1,Are there any troubleshoots or notes I should ...,Here are the troubleshooting notes from the Co...,"Yes! When baking cookies, it helps to start ch...",# Recipe chocolate chip cookies Notes Troubles...,2025-12-08T18:38:45.455050Z,2,3,2
4,2,"Give me the full recipe, step by step, to bake...",Here is the angel food cake recipe as provided...,Sure. Here are the ingredients for a perfect a...,# Angel Food Cake Recipe\nUsing only 6 ingredi...,2025-12-08T18:38:46.785380Z,5,5,5
5,2,Actually I don’t think I have those ingredient...,Here are the ingredients for the Easy caramel ...,"Yes, ofcourse! These are the ingredients for t...",225g softened salted butter\nplus extra for th...,2025-12-08T18:38:48.014249Z,5,5,5
6,2,"Great! I should have all those things, tell me...",Here are the Easy caramel cake ingredients and...,Here are the steps: \n1) Heat the oven to 180C...,## Easy caramel cake Method\n1) Heat the oven ...,2025-12-08T18:38:49.138466Z,5,5,5
7,3,Give me the ingredients to a lemon drizzle cak...,Lemon drizzle cake ingredients:\n\n- 225g unsa...,Here are the ingredients for a lemon drizzle c...,# Recipe Lemon drizzle cake Ingredients\n225g ...,2025-12-08T18:38:50.266012Z,5,5,5
8,3,Can I make this recipe gluten free? How?,Yes. To make this lemon drizzle cake gluten-fr...,"Yes, simply replace the self-raising flour wit...","To make this lemon drizzle cake gluten-free, s...",2025-12-08T18:38:52.753674Z,5,5,5
9,3,I don’t have eggs can I still make this recipe...,- For the lemon drizzle cake: Eggs are essenti...,Unfortunately no. Eggs play a crucial role as ...,Eggs play a crucial role in this lemon drizzle...,2025-12-08T18:38:53.773821Z,4,5,5
10,3,"Okay, let's make Gluten-Free Vegan Lemon pie. ...",Yes. The Gluten-Free Vegan Lemon Pie can use a...,"Yes, although almond will make it less creamy ...","You can use any type of plant-based milk, thou...",2025-12-08T18:38:55.079147Z,5,4,5
11,3,"I ran out of maple syrup, does honey work?",Yes. Honey can be used as a substitute for map...,"Yes, as the recipe says any other sweetener wo...","If you don’t have maple syrup on hand, feel fr...",2025-12-08T18:38:56.205147Z,5,5,5
12,4,Explain only why my macarons crack in the oven?,"- They weren’t left to dry long enough, so the...",Macarons usually crack when the shells don’t f...,Macarons where not left to dry long enough. Th...,2025-12-08T18:38:57.229563Z,5,5,5
13,4,Explain how can I fix it?,Here are the fixes listed in my baking guidanc...,The best way to prevent cracked macarons is to...,Make sure you let your macarons rest long enou...,2025-12-08T18:38:58.253136Z,4,4,5
14,4,Why are my macarons brown after baking? How ca...,- Why it happens:\n - Baking on too high a te...,Macarons usually turn brown when the oven temp...,Why it happened\nBaking on too high a temperat...,2025-12-08T18:38:59.276616Z,4,5,5
15,5,What is the art of chocolate tempering? And wh...,Here’s what the knowledge says about chocolate...,The art of chocolate tempering is the careful ...,Tempering chocolate is one of the foundational...,2025-12-08T18:39:00.402740Z,5,5,5
16,5,Why do I have to cool it all the way down and ...,Tempering is meant to shape the chocolate’s co...,Cooling the chocolate all the way down and the...,"To encourage this stable crystal form, chocola...",2025-12-08T18:39:01.325231Z,5,5,5
17,5,Do different chocolates use the same temperatu...,Not exactly. Different chocolates use differen...,Different chocolates do not use the same tempe...,Each variety contains different ratios of coco...,2025-12-08T18:39:02.348960Z,5,5,5
18,5,There are unmelted lumps in my chocolate now t...,Unmelted lumps can happen as chocolate cools. ...,Lumps usually appear when the chocolate wasn’t...,"Occasionally, as chocolate cools, unmelted lum...",2025-12-08T18:39:03.782771Z,5,5,5
19,5,Why did my chocolate turn thick and grainy?,Grainy and thick chocolate is often due to sei...,Chocolate turns thick and grainy when it overh...,"If the chocolate becomes thick, grainy, or une...",2025-12-08T18:39:04.910659Z,5,5,5
20,6,I’m trying to understand how long I should kne...,The knowledge I have doesn’t give a exact knea...,You’ll know your dough is sufficiently kneaded...,Dough that has been kneaded enough becomes smo...,2025-12-08T18:39:05.933467Z,3,4,4
21,6,What exactly is the windowpane test?,The windowpane test is a method to check glute...,It’s a simple check where you stretch a small ...,One of the most reliable ways bakers evaluate ...,2025-12-08T18:39:07.266442Z,4,5,4
22,6,And what happens if I knead too much?,"If you knead too much, the dough can become ov...","Over-kneading makes the dough tight, stiff, an...",kneading for too long can have the opposite ef...,2025-12-08T18:39:08.492842Z,5,5,5
23,6,"Okay, that makes sense. Should the dough still...",Yes. A well-kneaded dough doesn’t have to be c...,"Yes, properly kneaded dough can still feel sli...",Well-kneaded dough doesn’t have to be complete...,2025-12-08T18:39:09.824136Z,5,5,5
24,7,Why do cookies turn golden brown in the oven? ...,Cookies turn golden brown mainly because of he...,Cookies turn golden because heat triggers a re...,One of the most important of these is the Mail...,2025-12-08T18:39:11.406932Z,4,5,4
25,7,So is it the same thing as caramelization?,Not exactly. Browning in cookies comes from tw...,"Caramelization contributes to browning, but it...","Caramelization also plays a part, though it wo...",2025-12-08T18:39:12.272740Z,4,5,5
26,7,Is there a way to increase browning if my cook...,Yes. Browning is driven by Maillard reactions ...,You can increase browning in your cookies by e...,Maillard browning is influenced by temperature...,2025-12-08T18:39:13.410520Z,5,5,5
27,7,That’s interesting. Does this reaction happen ...,Yes. This browning happens in bread too—the cr...,"Yes, bread develops its crust through the same...",This browning process extends far beyond cooki...,2025-12-08T18:39:14.329802Z,5,5,5
28,8,What is Egg Coagulation in Baking?,"Egg coagulation is the process where, when egg...",Egg coagulation is the process where egg prote...,"When eggs are heated, their proteins unfold an...",2025-12-08T18:39:15.865941Z,5,5,5
29,8,What is Gelatinization of Starch in Baking?,Gelatinization is how starch behaves when heat...,Gelatinization happens when starch granules he...,As starch granules heat in the presence of moi...,2025-12-08T18:39:16.760445Z,5,5,5
30,8,Why does whipping egg whites make them so stiff?,"Whipping egg whites introduces air, and the pr...",Whipping egg whites traps air and causes their...,"Whipping egg whites introduces air, allowing p...",2025-12-08T18:39:17.913455Z,5,5,5
31,8,Why does over whipping them change them?,Whipping egg whites traps air and the egg whit...,"When egg whites are whipped too long, the prot...","if beaten for too long, the network becomes ov...",2025-12-08T18:39:19.039906Z,5,5,5

In [165]:
df_expanded["groundedness"] = pd.to_numeric(
    df_expanded["groundedness"], errors="coerce"
)

In [166]:
avg_by_dialogue = (
    df_expanded
    .groupby("dialogue_id")[["factual_accuracy", "helpfulness", "groundedness"]]
    .mean()
    .reset_index()
)

In [167]:
avg_by_dialogue

   dialogue_id  factual_accuracy  helpfulness  groundedness
0            1          3.250000     3.750000          3.00
1            2          5.000000     5.000000          5.00
2            3          4.800000     4.800000          5.00
3            4          4.333333     4.666667          5.00
4            5          5.000000     5.000000          5.00
5            6          4.250000     4.750000          4.50
6            7          4.500000     5.000000          4.75
7            8          5.000000     5.000000          5.00

In [168]:
#saving scores
avg_by_dialogue.to_csv("avg_by_dialogue_llm_judge.csv", index=False)

In [169]:
overall_avg = avg_by_dialogue[["factual_accuracy", "helpfulness", "groundedness"]].mean()
print(overall_avg)

factual_accuracy    4.516667
helpfulness         4.745833
groundedness        4.656250
dtype: float64

In [170]:
#saving average scores
with open("overall_avg_llm_judge.json", "w") as f:
    json.dump(overall_avg.to_dict(), f, indent=4)